### ISSUE TITLE
GTA Working Directory should have $(ProjectDir) as a placeholder

### ISSUE THREAD

**Issue by StevilKnevil** [csoltenborn/GoogleTestAdapter#100]
Currently the only placeholders are SolutionDir and ExecutableDir.

However our working directory need specifying relative to the project (not the solution)

**Comment by csoltenborn** [comment]
Congrats for opening our issue 100! :-)

But I'm sorry to say that this is once more not possible as far as we know. As a matter of fact, we provide the solution dir placeholder since the solution dir is passed as part of the config we receive from VS when our adapter code is called (except if it is called from VsTestConsole.exe). However, we do not have any information about project dirs, so we can not provide that information to our users either.

You can use the `$(SolutionDir)` or `$(ExecutableDir)` placeholders as a starting point for providing the path to your desired working dir - if that isn't possible, than I fear you are out of luck :-|
