### ISSUE TITLE
No StackTrace when .sln file location is deeper then the code files

### ISSUE THREAD

**Issue by ninjaCoder** [csoltenborn/GoogleTestAdapter#125]
First of all thank you for this great plugin, its really useful.

It seems there is relation between the location of .sln file to the presents of the StackTrace when tests fails.
For example, when the files are in the following layout (the .sln file is **inside** ConsoleApplication1 directory):
ProjectDir/
__ Code/
____ gtest/gtest.h
____ gtest-all.cc
____ Source.cpp
__ ConsoleApplication1/
____ ConsoleApplication1.vcxproj
____ ConsoleApplication1.vcxproj.filters
____ StackTrace_NotWorking.sln

There is not StrackTrace in the output window and the message has the file name and location:
![pic0](https://cloud.githubusercontent.com/assets/26801754/24526460/e8204724-15a6-11e7-8727-2d50ce36304b.jpg)

**BUT !!!** When I move the .sln file one directory upper to the ProjectDir, without changing the code nor the project file as follow (the .sln file is **outside** ConsoleApplication1 directory):

ProjectDir/
__ Code/
____ gtest/gtest.h
____ gtest-all.cc
____ Source.cpp
__ ConsoleApplication1/
____ ConsoleApplication1.vcxproj
____ ConsoleApplication1.vcxproj.filters
__ StackTrace_WorkingGood.sln

The test output now is with the StackTrace correctly:
![pic2](https://cloud.githubusercontent.com/assets/26801754/24526025/4633c6bc-15a5-11e7-8c4c-74cbccb933b6.jpg)

**Comment by csoltenborn** [comment]
Thanks for your bug report! Here's what's happening:

* To extract the location of the error from the Google Test output, we rely on the solution directory. The according regex looks as follows: `$@"({solutionDir}{ValidCharRegex}*)(?::{line}|\({line}\):)(?::? {error})?"` (I'm not showing the definitions of `ValidCharRegex`, `line`, and `error` here - see our `ErrorMessageParser` if you are interested!).
* In case of your solution structure, the solution directory appears to be the `ConsoleApplication1` directory (since that's the directory containing the `.sln` file).
* Thus, our code tries to find the string `..\ConsoleApplication1..` within the error message produced by Google Test. If it doesn't, it prints the complete error message (as you can see in your broken example), but doesn't produce an error stack trace.

Our approach should work fine as long as the source code is contained somewhere within the solution directory (as you have correctly analyzed), which is not the case for your solution. I'm not sure whether we can (and should) change that - to be honest, I think that your solution structure is rather uncommon (that's why we haven't seen such problems by now). 

Is there any particular reason for your solution structure? Providing a valid use case might make us think harder about how to support solution structures like yours ;-)

**Comment by csoltenborn** [comment]
I had to learn today that your solution structure is not that uncommon. Would you mind to check whether [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.9.1.721/artifacts) fixes your problem?

**Comment by ninjaCoder** [comment]
I tested the new build and the problem was fixed :-)

Thank you for your quick answer and the quick fix.

If it's possible I would recommend to print a warning message in case of any other problem with the XML report parsing.

**Comment by csoltenborn** [comment]
Sweet, thanks for testing! We will think about whether we can produce warnings in such cases...
