### ISSUE TITLE
Test output parser confuses exception message with error location

### ISSUE THREAD

**Issue by gobater** [csoltenborn/GoogleTestAdapter#157]
Hi,

I have a strange behavior with GoogleTestAdapter in tests that throw exceptions

The output of the window looks like the following file: [test_output.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/1211640/test_output.txt)

The test result window shows the following for "Test.WithStackTrace" (filename string is cut)
![image](https://user-images.githubusercontent.com/23657567/29122575-182d1ed2-7d13-11e7-8839-f3daf72db57e.png)

However, for "Test.WithoutStackTrace" shows the following (correct exception text, but no StackTrace)
![image](https://user-images.githubusercontent.com/23657567/29122663-66ed7ff8-7d13-11e7-9c99-c18971185f1c.png)

As you can see, the GoogleTestAdapter, does not parse correctly the test output. Notice the dash ("-") after the ":" at the end of the filename in the exception text of "Test.WithoutStackTrace"

I would expect to see the correct text (result message) and the Stack Trace in both tests

You can reproduce the failures with the following code
[example_code.cpp.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/1211427/example_code.cpp.txt)

**Comment by csoltenborn** [comment]
Now that's what I call a bug report! 👍 

However, the adapter's behavior is not as strange as it looks - here's the output your sample code produces:
```
[----------] 2 tests from Test
[ RUN      ] Test.WithStackTrace
unknown file: error: C++ exception with description "Assertion failed in c:\users\chris\git\googletestadapter\sampletests\tests\basictests.cpp:174" thrown in the test body.
[  FAILED  ] Test.WithStackTrace (1 ms)
[ RUN      ] Test.WithoutStackTrace
unknown file: error: C++ exception with description "Assertion failed in c:\users\chris\git\googletestadapter\sampletests\tests\basictests.cpp:-179" thrown in the test body.
[  FAILED  ] Test.WithoutStackTrace (0 ms)
[----------] 2 tests from Test (3 ms total)
```
The `unkown file` part is the place where gtest prints out the location of the assertion failure - that's what we use to produce the stack trace element.  Now, your *TestWithStackTrace* has an error message containing the exact same format we are looking for when trying to figure out the stack trace element (i.e., `file:line`), and that apparently confuses our parser: it produces a stack trace element from the exception message, and that part is then not used any more for the test's error message. This is the *bug* part, so to speak.

Your *TestWithoutStackTrace* does not have this problem due to the inserted `-` and therefore behaves correctly. I fear that Google is to blame here for not providing error location (and thus, we cannot provide a stack trace element).

Of course, we can not rely on the exception message containing the exception's location. We will still try to fix the first problem!

**Comment by gobater** [comment]
Hi Chris,

Basically, you are telling us that GoogleTestAdapter produces a StackTrace in the first case just "by luck". Only because our Exception text contains the `file name` ":" line (since Google does not procude in this case the correct Output? Wow! Impressive how Lucky we are here!


Thanks for your support

**Comment by csoltenborn** [comment]
You're welcome. Sometimes, all you need is luck :-)

**Comment by gobater** [comment]
and... I am still going to have "luck" after your fix? --> in case that google is not able to provide the information concerning the file producing the exception but message contains valid information, are you going to keep the old behavior?

**Comment by csoltenborn** [comment]
No, I don't think so... That's what I meant with "we can not rely on the exception message containing the exception's location". I think you are being stuck with the location of the test case itself. 

However, have a look at our (i.e., gtest's) option [Catch exceptions](https://github.com/csoltenborn/GoogleTestAdapter/blob/fd10b8110bf0f057ed73463223412502b1925272/GoogleTestAdapter/Core/Settings/SettingsWrapper.cs#L448), which might be what you need!
