### ISSUE TITLE
VS2017 grinds to a halt whenever the Test Explorer window is showing

### ISSUE THREAD

**Issue by ChaosCabbage** [csoltenborn/GoogleTestAdapter#171]
Hi! Thanks for all the work on this extension. It's very useful, except...

I'm working on a pretty big project, and I'm experiencing some hefty slowdowns with this extension. 
The slowdown only happens when the Test Explorer pane is actually visible. This is very consistent - there is a noticeable difference as soon as I open or close the pane.

Some details:
 - The solution contains 490 C++ projects which are all built as DLLs using the VS2013 toolset.
 - I have selectively built a few test projects, and there are 369 tests showing in the explorer.
 - When the Test Explorer window is showing, Visual Studio consumes a constant 18% of the CPU.
 - When I close the window, it drops to around 2% of the CPU.

As long as that window is closed, I can happily run and debug tests. 

Extension version: 0.11.1.895

(If I have some time, I'll try to do some profiling and figure this out. I have a bit of experience with writing VS extensions.)

**Comment by csoltenborn** [comment]
Ok, that's indeed what I'd call a huge solution... Thanks for your offer to profile the extension! That's of course greatly appreciated in case we can't figure this out.

Here are a couple of things you can try to speed up test discovery (which is probably the issue here):
* Switch off *Parse symbol information*. You won't have source locations and traits from macros, but will still get clickable stack traces in case a test fails. This will avoid scanning the executables' `.pdb` files.
* Configure a regex matching all of your test executables (and only those), or create `.is_google_test` files. This will avoid scanning all changed executables during test discovery.
* Make sure *Print debug info* and *Print test output* are `false`. (Enable these options and *Timestamp output* to get a better idea on the cause.)
* Try [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.12.0.901/artifacts), which contains a performace fix that should speed up test discovery for huge numbers of tests.

I'm curious which of these approaches do or do not help, since your solution is the biggest one I've heard of that's used with GTA :-)

**Comment by ChaosCabbage** [comment]
Thanks for the suggestions! 
The regex made an immediate difference. I didn't realize that feature existed. 

I'm going to do a few more experiments, though. e.g. What happens if I build all 245 test projects? 
If it's slow again at that point, I'll try the other suggestions, and report back.

**Comment by csoltenborn** [comment]
You're welcome! Looking forward to hearing your results...

**Comment by ChaosCabbage** [comment]
With the regex in place, it seems completely happy with hundreds of test executables, so I'm happy to close this!

**Comment by csoltenborn** [comment]
Good to hear :-)
