### ISSUE TITLE
Google Test Adapter not Available as New Test Project in Vs2015 Update 3

### ISSUE THREAD

**Issue by dschwartz1957** [csoltenborn/GoogleTestAdapter#183]
Hi Christian,

I am using Visual Studio 2015 Enterprise  (14.0.25431.01) Update 3 and just installed Google Test Adapter Version 0.12.1.966 via "Tools -> Extenstions and Updates".  I verified that GTA is installed and can be configured under "Tools -> Options". 

I want to write unit tests for an existing project C++ project.  When I use the new project wizard to create a C++ Test project, Google Test Adapter does not appear as a project type, only "Managed Test Project" and "Native Unit Test Project" (see the screen shot below). Is this feature supported in Vs2015, or do I create the test source files and discover them in Test Explorer? There is a screen shot in a Microsoft blog post that shows Google Test as an option in Vs2017.

Thank you,

David Schwartz

![image](https://user-images.githubusercontent.com/13773723/33493681-d539e206-d68e-11e7-9b7a-0a6703c40873.png)

**Comment by csoltenborn** [comment]
I fear that you are a couple of weeks too early ;-)

This feature is not yet available (see #177), but will be released in the not-too-far future. The Test Adapter for Google Test (which is a fork of GTA and is maintained by Microsoft) already has a project template - that's where the screenshot is from. However, TAfGT is only available for VS2017, so that's probably not an option for you. Stay tuned...

If you don't mind, I will close this issue - keep an eye on #177!

**Comment by dschwartz1957** [comment]
Hi Christian

Thanks for the quick response. I look forward to your enhancement. It will
be a challenge adding unit tests to a large, legacy application. GTA will
certainly help.

David
