### ISSUE TITLE
"Could not find out VisualStudio version: Access denied" message from build server

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [csoltenborn/GoogleTestAdapter#204]
We have a TFS 2013 build server and we use GoogleTestAdapter for gtest projects. The tests are discovered, are run and all pass without a problem on the server.

However the test run fails because of an error message "Could not find out VisualStudio version: access is denied". I checked the repository and it seems VsVersion class emits such message.

We are using VisualStudio 2013 on our build server and GTA is used as a nuget package. I have also tried manually copying GTA binaries into "Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions" directory but the results were the same.

Is there an option or an environment variable to modify before running our tests?

**Comment by csoltenborn** [comment]
No, I don't think so. To make sure that I correctly understand your issue: Does the error message make your build fail although all tests pass? That's indeed a pity :-)

GTA tries to figure out the VS version by traversing the process hierarchy of the process it's running in and looking for a process named `devenv.exe` or `vstest.console.exe`, and then looking up the version within the process' binary. Apparently, this fails because of insufficient rights. I haven't seen this before and would thus guess that maybe your build server's configuration is too restrictive...

**Comment by zahirtezcan-bugs** [comment]
The error message makes the build "Partially Succeeded" instead of "Succeeded in TFS build terms. It is not a fail per se. But when we see the pictures or graphs about the builds the color is orange instead of green and that increases the tension:)

I am internally trying to make an environment variable solution to this problem, just inside VsVersion.cs. If I succeed I can send a pull request.

**Comment by csoltenborn** [comment]
I feel you... I would still recommend to investigate the actual case that this doesn't work on your particular build server, since if the processes running test discovery and execution code are lacking permissions, this might also affect your test results (and since I haven't seen this problem, I'd guess that there's something unusual going on on that machine).

What's the idea here? Providing the version via an env variable, and don't try to walk the process tree if that variable is set?

**Comment by zahirtezcan-bugs** [comment]
As you suggested, I have put some logging into the process chain inspection code and the results have shown that the tests are  being run by "vstest.executionengine.exe" instead of "vstest.console.exe". This causes the recursion go deeper and it tries to inspect "tfsbuildservicehost.exe" and its predecessor. This is where the access denial happens.

Yes the idea was to put an environment variable that contains the version information. But, the implementation was much more complex than I intended so I forfeit :)

Instead I plan to prepare a regex for parent processor name, because there are many executables that may run for other build definitions such as "vstest.executionengine.x86.exe", "vstest.executionengine.x86.clr20.exe" etc.

The regex for process name match may be "(^vstest\..*\.exe$)|(^devenv\.exe$)".

**Comment by csoltenborn** [comment]
Interesting... Afaik, VS spawns two processes, i.e., for test discovery and test execution. You have met the former one. However, I thought that these processes are spawned either by `devenv.exe` or by `vstest.console.exe`... Your regex approach should be fine as long as the version information GTA is looking for is also contained in the respective executables.

**Comment by csoltenborn** [comment]
One more question: Can you provide some information on how tests are run by TFS 2013, e.g. the configuration of the according build step? I'm still a bit puzzled that `vstest.console.exe` isn't involved into the fun...

**Comment by zahirtezcan-bugs** [comment]
I was mostly unaware of the process until 3-4 weeks ago to be honest. They had a xaml build template (which is deprecated in newer versions of the TFS afaik), which has a testing step. The build definition is named as TfvcTemplate, which is the mostly used one I guess from the stackoverflow and similar sites.
