### ISSUE TITLE
Debugging GTA experimental mode in VS throws access violation

### ISSUE THREAD

**Issue by shamusn** [csoltenborn/GoogleTestAdapter#220]
Hi,

I love the GTA and it is has been very helpful.
I am having trouble getting it to work on my newer PC.

Debugging the unit test GTA in VS doesn't work and throws an access violation.
![accessviolation](https://user-images.githubusercontent.com/40246237/41370586-12f44544-6f16-11e8-90c0-a4b8e5188b02.PNG)
Any ideas?

Changing this experimental setting to false, gets passed the access violation
![13jun2018_gtaexperimental](https://user-images.githubusercontent.com/40246237/41370292-3c1645f4-6f15-11e8-8f6d-9c58f25278ac.jpeg)
I am able to debug when debugging the project from VS 2013 Update 4.
![vsdebug](https://user-images.githubusercontent.com/40246237/41370381-7abba786-6f15-11e8-8b10-c63015d135e3.jpeg)
Listing the tests from command line works.
![gtest_list_testsworks](https://user-images.githubusercontent.com/40246237/41370460-b7f9c948-6f15-11e8-9f8f-51bd503939a7.jpeg)
Running the test from GTA in VS works.

It works on some machines with VS 2013 Update 4, Windows 7, GTA version 0.12.3.994.

thanks

**Comment by csoltenborn** [comment]
Interesting... Could you please check out whether MS' version of  the adapter (Test Adapter for Google Test) has the same issue?

**Comment by csoltenborn** [comment]
Thanks for your great bug support... On which version of VS do you have the problem? You  only mention that it works on some machines, are the other ones also running VS2013 update 4?

If that's the case, forget about TAfGT (VS2017 only). Since the exception happens within your test executable, I do not see how GTA could cause that exception. The debugger is attached differently between the two execution modes, which might explain why only one debugger config catches it (I would consider this a bug, btw :-) ).

My recommendation is that you try to figure out where exactly the access violation is happening. As a side note, I have seen unexpected exceptions with current commits of the gtest repository, so make sure you are using a release version.

**Comment by csoltenborn** [comment]
Closed due to inactivity - feel free to reopen if problem remains.

**Comment by csoltenborn** [comment]
Don't worry, just trying to keep my issues clean...

No, TAfGT (Test Adapter for Google Test) is Microsoft's clone of GTA which is delivered through the VS installer, but is VS2017 only. 

The VS test framework provides API to launch processes with a debugger attached. However, it is not possible to get the process' output during execution, which has a couple of drawbacks fo GTA. Therefore, GTA has implemented an own way to attach a debugger to a process. The *new execution framework* option results in that own implementation being used.

However, I'm pretty optimistic that switching between those two options will not cause your code to throw access violations. Therefore, I would try to figure out the actual cause of those violations.

If you can provide a sample solution which reproduces this problem, I would try to figure out why the two ways to attach a debugger behave differently, but no promises on that, since I do not have a lot of knowledge in that area (and also haven't seen this problem before).

**Comment by shamusn** [comment]
Hi Christian,

For VS 2013 update 4, if the "new execution framework" option is disabled, what do we lose?  
Will the test results still show in the Google Test log output?
Will the test results still show in the VS debugger output window?

thanks
-shamus

**Comment by csoltenborn** [comment]
I think these are the major differences (all during debugging):
* No test output on the test output window (this is probably what you mean with "Google Test output log"!?)
  * Note that there is no output on the VS debug window (at least not intentionally :-) ), independent from the execution framework used
* No test crash detection (=> behavior slightly differs between execution and debugging)
* Less responsive test window (test results are only available to GTA after test executable has finished)
* Slower test execution (VS <2017 contains a bug which causes it to loose test results, which forces GTA to throttle test result reporting - this has much less effect if the test results are reported to VS "on the fly" as in the new execution mode)
* no indication of "the tests currently executed"

**Comment by shamusn** [comment]
Thanks Christian.
I am not going to be able to resolve this.
All I can see is that if that "new framework" option is enabled, then I get the error.  Otherwise, I do not.
GTA is working well enough for me.

thanks for providing this extension.
