### ISSUE TITLE
Cannot open test (F12) from Test Explorer

### ISSUE THREAD

**Issue by MrPythagoras** [csoltenborn/GoogleTestAdapter#232]
Hi,

Thank you for your great work!

I want to be able to open Tests from the Test Explorer, by either using the context menu or hitting F12. This does work for my project in Debug mode, but not in Release. I could figure out, that it works in Release as well, if I allow generating debug info in the linker property. Alas, this is exactly what I want to avoid. 

Do you have any ideas how to solve the problem?

Thanks in advance =)

**Comment by csoltenborn** [comment]
Thanks for the kudos :-)

No, that's not possible, I'm afraid, since the debug info is exactly where GTA gets the source locations from... However, note that you only have to generate the debug info for your test projects (not for your projects under test) - maybe that's an acceptable compromise for you...

**Comment by MrPythagoras** [comment]
I feared so, but I guess it is an acceptable compromise. Thanks a lot!

**Comment by csoltenborn** [comment]
You're welcome!
