### ISSUE TITLE
GTA does not detect VS2019 16.1 Preview

### ISSUE THREAD

**Issue by trkrogstad** [csoltenborn/GoogleTestAdapter#286]
The vsix-installer does not seem to detect VS2019 16.1 Preview 2.0. Could it be some version number expectation? GTA is not present in the "Manage Extension"-plugin when searching the online Marketplace either, which I guess could be related. Probably a quick change of the vsixmanifest is sufficient: https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by csoltenborn** [comment]
Interesting... I had increased the target version (otherwise GTA would not be able to install into VS2019 at all). However, I have realized the changes as suggested by your link (thanks!) within [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/builds/24275808/artifacts) - would you mind to give it a try?

**Comment by trkrogstad** [comment]
I can confirm that the version you linked to in the previous post detects 2015, 2017, and 2019 preview 2.0 when running the vsix. So it seems to fix the problem.

**Comment by csoltenborn** [comment]
Ok, thanks! Will probably release an update at the weekend...

**Comment by csoltenborn** [comment]
Fixed with PR #287
