### ISSUE TITLE
Debug Error crash at startup

### ISSUE THREAD

**Issue by edenroz** [csoltenborn/GoogleTestAdapter#325]
Version:
GoogleTestAdapter 0.10.1.7 from VS marketplace
Visual Studio 15.19.35

As soon i start up VS or click "run all" i get this error:
![image](https://user-images.githubusercontent.com/12448316/118089641-deef7c00-b3c8-11eb-99e3-10199f92a276.png)
 If i delete the .vs directory everythng works again untill reboot.

I'll test this issue with Visual Studio 15.19.36 asap.

**Comment by csoltenborn** [comment]
I think this is because your test executable crashes (probably already at test discovery time), and that you trigger test discovery by deleting the .vs directory. You can check this by running the executable from the command line - it will probably still crash.

You can "simulate" test discovery by configuring your solution such that the test in question can be run via F5 (i.e., pass the test discovery arguments at Project properties -> Configuration Properties -> Debugging -> Command Arguments) and then step through your test executable.

Note that if I remember correctly, the used arguments for invocation of the test executable are print to the Test output window if GTA's Debug mode is enabled, so you can get them from there (and use them for the above "run via command line" and "run via F5" options.

**Comment by csoltenborn** [comment]
Closed due to inactivity...
