### ISSUE TITLE
Can it run under Linux?

### ISSUE THREAD

**Issue by KlausDr** [csoltenborn/GoogleTestAdapter#327]
I wonder if the GoogleTestAdapter can run under Linux. I tried:

```
dotnet /usr/share/dotnet/sdk/3.1.404/vstest.console.dll /TestAdapterPath:$HOME/.nuget/packages/googletestadapter/0.18.0/ /Platform:x64 <path to my test exe>
```

but got the error:
  Unable to find /home/admin/git/CMF/Bin/x64/LinuxDebug/CmnDSTRCParserGUnitTests.deps.json. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk".

Under Windows the same test can be used with GoogleTestAdapter.

**Comment by csoltenborn** [comment]
Sorry for the slow response... I don't think that this can work since GTA depends on the .NET framework (not .NET Core). I'm not sure whether this could be changed easily, and I'm not active Linux user, so this is a bit hard to test for me.

In case you want to have a try, please let me know - I'd be happy to provide support on getting everything to build and stuff...
