### ISSUE TITLE
Unit tests don't honor "On Run, when build or deployment errors occur" option

### ISSUE THREAD

**Issue by loki980** [csoltenborn/GoogleTestAdapter#34]
Looked at the following, hoping it would solve this issue:
http://stackoverflow.com/questions/596142/would-you-like-to-continue-and-run-the-last-successful-build

However, it seems that "Run test" doesn't honor this setting.  Is this something inherent to VS or is this something that can be changed in the extension?  Thanks!

**Comment by csoltenborn** [comment]
I don't think that we have any influence on that one - the adapter just receives a set of executables or test cases to be executed, but no information at all about the state of the last build. Plus, we cannot access the VS instance we are running in since the test code is executed in different processes. Thus, my guess is that every single test adapter out there has that issue. If you know one that doesn't, please let us know, we will than investigate the (hopefully accessible) source code. 

Sorry for that - closing the issue...

**Comment by loki980** [comment]
Yeah, ended up finding people that were complaining this wasn't possible in any test adapter/runner in VS.  Here's an AHK script to do it for you:

```
;************************
;Automatically say "no" to visual studio failed build errors that prompt to re-run tests from last successful build
;************************
#Persistent
SetTimer, lookForBuildFailPopup, 100
return

lookForBuildFailPopup:
	IfWinActive, Microsoft Visual Studio, There were build errors
	{
	  	ControlFocus, No
	  	Send {Space}
		Sleep, 2000
	}
	return
```

**Comment by csoltenborn** [comment]
Great, I might use that script at work - it's not that I'm not annoyed by that stupid dialog :-)
