### ISSUE TITLE
Add option to specify working directory

### ISSUE THREAD

**Issue by synts** [csoltenborn/GoogleTestAdapter#71]
I'd like to be able to specify the working directory. My setup usually is writing and debugging via my test runner in Visual Studio. This has the working directory set to the solution directory. Various test configuration and test data files are loaded relative to this path. Running via the test adapter fails for me since the working directory is set as the output executable directory. For me that is e.g. $(SolutionDir)\x64\Debug where I have builds for x64, win32, debug and release. Would this be possible?

**Comment by csoltenborn** [comment]
It certainly is. In fact, Jonas and I have discussed this very enhancement a couple of days ago...

However, it will take some time, since providing a general option does not suffice here - we need to be able to specify different working dirs for every test executable of the solution.

Can you in the meantime fall back to copying your config and data files to your build directory? You should be able to do this with VS or even with GTA's test setup batch file...

**Comment by csoltenborn** [comment]
Just to let you know: We decided to implement the whole settings enhancement step by step, and the first step allows to specify the working dir on solution level. Thus, if all test projects of your solution need the same working dir, this will already be possible with the next release. Therefore, I'm already closing this issue - if you need more fine-grained working dir configuration, watch issue #74

**Comment by synts** [comment]
Awesome. Solution level setting is working for me and my setup. Thanks!
