### ISSUE TITLE
Failed tests results do not contain link to the line which is failed

### ISSUE THREAD

**Issue by SDxKeeper** [csoltenborn/GoogleTestAdapter#79]
Right now there are only option to click on the link for "Source" of the test and jump to test start.

But when Unit test fails, there are no option to navigate directly to failed line, even if "Message" contains it.

In other IDE (i.e. QTCreator) there are option to jump directly to the line mentioned in the "Message" container.

**Comment by csoltenborn** [comment]
We do try to parse the error messages and provide links to the failed assertions, but maybe parsing fails for some specific messages... Are you able to provide a simple example C++ solution containing tests which have that problem? Altenatively, you could execute your test executable and provide a) the complete output produced by the test executable (preferrably as a text file) and b) the XML result file (as produced by option `--gtest_output "xml:MyResultXmlFile.xml"`) - we will look into it and fix the parsing if necessary.

**Comment by csoltenborn** [comment]
Did you already have the chance to create the output and XML file as described above, or did you find another solution for your problem? Either way, please leave a short note here - if the problem's solved, we'd like to close this issue, otherwise, please let us know how we can help.

**Comment by SDxKeeper** [comment]
hi Christian,

After playing a bit with the adapter I've found that its probably not possible to make in the current design.

Anyways i've created simple test to explain what I saw in other systems which work with google test.
As you  can find in attachment error happened at basictests.cpp:23 and it's stated in the message which you parse out into Test Explorer. 
But link which is displayed after Source variable will lead to the start of the test, it would be better to jump directly to the line indicated in the message.
[example.zip](https://github.com/csoltenborn/GoogleTestAdapter/files/511742/example.zip)

One more thing which I stepped on is regex for executable discovery. Default one is too strict, not everybody names their tests as test.exe or tests.exe
I would reccomend upgrading to something less strict: ([Uu]nit)?[Tt]est[s]?(.+)?\.exe

**Comment by csoltenborn** [comment]
Hi SDxKeeper,

thanks for the example code! However, it leaves me a bit confused, since the example works just fine on my machine (see screenshot below - I've copied your example code into our BasicTests.cpp; you can see that the link points to the correct line (and it indeed works).

Thus, this raises the question what is different between our systems. Which edition and version of VS are using, and in which language?

Btw: What do you mean with "probably not possible to make in the current design"?

The current default regex is for sure not the nicest one imaginable, but we have done this at least partly for a reason: We do not want to have matching executables which are not Google Test executables, and if the regex doesn't suite your project, you can provide a custom one through our adapter's settings. However, Jonas and I will discuss whether it's a good idea to change to a default regex in the line of your suggestion.

![image](https://cloud.githubusercontent.com/assets/352576/19141824/f8cb514c-8b98-11e6-9ff3-da1144591455.png)

**Comment by csoltenborn** [comment]
Did you by any chance figure out why our test adapter would not provide links to assertion failures for you?

**Comment by csoltenborn** [comment]
Closed because of inactivity - feel free to reopen if you still have problems or if you can contribute any insights...

**Comment by SDxKeeper** [comment]
Ok, sure. I'll have chance to play with it next month.

29 окт. 2016 г. 12:27 PM пользователь "Christian Soltenborn" <
notifications@github.com> написал:
