### ISSUE TITLE
Makefile project

### ISSUE THREAD

**Issue by stamerlan** [csoltenborn/GoogleTestAdapter#86]
Hello,

Is it possible to use this extension with makefile projects?

**Comment by csoltenborn** [comment]
Can you please provide a bit more context on your use case? In particular, do you want to use our extension from within Visual Studio?

**Comment by stamerlan** [comment]
Hello,

I created Makefile project in VS 2015 Community Edition. I use external make and gcc (from mingw) to build project. But I failed to discover tests in Test Explorer (output file name is test.exe). Am I done smth wrong or Makefile projects are not supported?

**Comment by csoltenborn** [comment]
We haven't tried that kind of projects, so I don't know. Have you checked out our trouble shooting section?

Here's what I would try: First of all,  enable our adapter's *Print debug info* option. When your build is finished, the adapter prints information about the executables reported to it by Visual Studio, and whether they match the test discovery regex (the output ends up in the test output window). If your executable doesn't show up, than that's a bad sign, since VS doesn't seem to know about it, and thus, our adapter can't know about it (in this case, it would be nice if you could provide a self-contained, minimal sample solution such that we can check whether there is anything we can do about that). If it shows up, but the regex doesn't match, set up your own *Regex for test discovery*. Let us know if that helped!

**Comment by stamerlan** [comment]
Hello,

I made a simple makefile project which can be built using nmake and vs compiler (so you shouldn't have any problems with external tools). 
I found that if output executable is placed in the project's directory it successfully discovered, but if it placed into another directory it is not visible for your extension (even no log output).

Attach contains a solution for vs2015. To build it you need to change GOOGLE_TEST_DIR variable to google test framework directory on your machine in file test_mk/Makefile. 
If you set variable OUT to "test.exe" test will be discovered, if you set it to "out/test.exe" - no.

[test_mk.zip](https://github.com/csoltenborn/GoogleTestAdapter/files/570464/test_mk.zip)

**Comment by csoltenborn** [comment]
That's in the direction of what I guessed... thanks for the sample solution, I will look into this in the next couple of weeks! We might just add an option to explicitly add certain test executables (which can not be found by Visual Studio).

I hope it's ok for you that I change the title of this issue a bit.

**Comment by csoltenborn** [comment]
I think we've found out the actual problem with your solution: The NMake settings of your project contain a setting `Output` which just points to `test.exe`. This is the place where to tell VS about the location of the generated executable. We assume that this setting is populated when importing your makefile project into VS - however, if you change the `out` variable of your makefile, the two locations are not consistent any more. Another sideeffect of this is that you cannot launch your project with `F5`.

Thus, if you make sure that these two locations are configured consistently, everything should be fine.

I will add this information to our trouble shooting section - thanks once more for the example solution!
