### ISSUE TITLE
Generalize the plugin to work for boost tests [Feature request]

### ISSUE THREAD

**Issue by ftrofin** [csoltenborn/GoogleTestAdapter#88]
This plugin is very cool and I like that it is has some flexibility in its settings (like test discovery regex and traits) that make it easier to adopt it in a larger variety of projects. 

I was wondering how much effort would be to refactor it so it can work with boost tests? Yes, I know there is another plugin made for that but why having two plugins when you can have only one? It seems to me that the core functionality is the same and only small percentage of the code would need to be changed.

Cheers,

Florin

**Comment by csoltenborn** [comment]
Hi Florin, our adapter is only supposed to work with Google Test (in fact, I assume that most of its code will not be reusable even if we would consider adding Boost support). Since the VS test framework is designed to support different test adaptes in parallel, and since there already is an extension for executing Boost tests, I don't think it would be a good idea to enhance our adapter with that functionality - let's instead focus on providing the best Google Test support we can come up with.

If you want to give it a shot, let us know, and we can discuss how we can help - but as I said, I don't think it's worth the effort... hope you are ok with this decision.
