### ISSUE TITLE
Debug Test should respect the startup directory specified in the project settings.

### ISSUE THREAD

**Issue by StevilKnevil** [csoltenborn/GoogleTestAdapter#97]
If I debug normally, the current working directory is set to the value specified in the project settings.

If I debug a test from the UI, the current working directory is set to the location of the executable.

This means I get different results depending on which way I debug the test.

Ensure that 'run' from the UI also respects the working directory specified in project settings.

**Comment by csoltenborn** [comment]
I fear this is not possible. The problem is that we are running under different circumstances, and project settings are not available under some of them (think VsTest.Console.exe). 

However, in case you haven't seen it: the GTA *Working directory* setting allows to, err, set the working directory and can also be provided on build servers via a test settings file. Hope this helps!

**Comment by StevilKnevil** [comment]
Yes thanks, that should help.

See also:
https://github.com/csoltenborn/GoogleTestAdapter/issues/100
